import type { Metadata } from "next";
import { EB_Garamond, Noto_Sans } from "next/font/google";
import "./globals.css";
import { Providers } from "app/providers";
import { getServerUser } from "entities/user/server/get-server-user";
import type { ReactNode } from "react";

const notoSans = Noto_Sans({ subsets: ["cyrillic"], variable: "--font-sans" });
const ebGaramond = EB_Garamond({
  subsets: ["cyrillic"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Сад Для Вас",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const preloadedUser = await getServerUser();

  return (
    <html lang="ru" className={notoSans.variable}>
      <body className={`${ebGaramond.variable} antialiased`}>
        <Providers preloadedUser={preloadedUser}>{children}</Providers>
      </body>
    </html>
  );
}
