import type { Metadata } from "next";
import { EB_Garamond, Noto_Sans } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";
import { Providers } from "@/app/providers";
import { getServerCart } from "@/entities/cart/server/get-server-cart";
import { getServerUser } from "@/entities/user/server/get-server-user";

const notoSans = Noto_Sans({ subsets: ["cyrillic"], variable: "--font-sans" });
const ebGaramond = EB_Garamond({
  subsets: ["cyrillic"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Сад Для Вас",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const preloadedCart = await getServerCart();
  const preloadedUser = await getServerUser();

  return (
    <html lang="ru" className={notoSans.variable}>
      <body className={`${ebGaramond.variable} antialiased`}>
        <Providers preloadedCart={preloadedCart} preloadedUser={preloadedUser}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
