import type { Metadata } from "next";
import { EB_Garamond, Noto_Sans, Noto_Serif } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";
import { Providers } from "@/app/providers";
import { getServerCart } from "@/entities/cart/server/get-server-cart";
import { getServerComparison } from "@/entities/comparison/server/get-server-comparison";
import { getServerUser } from "@/entities/user/server/get-server-user";

const notoSans = Noto_Sans({ subsets: ["cyrillic"], variable: "--font-sans" });
const notoSerif = Noto_Serif({
  subsets: ["cyrillic"],
  variable: "--font-logo",
});
const ebGaramond = EB_Garamond({
  subsets: ["cyrillic"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Сад Для Вас",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const [preloadedCart, preloadedUser, preloadedComparison] = await Promise.all(
    [getServerCart(), getServerUser(), getServerComparison()],
  );

  return (
    <html lang="ru">
      <body
        className={`${ebGaramond.variable} ${notoSerif.variable} ${notoSans.variable} antialiased`}
      >
        <Providers
          preloadedCart={preloadedCart}
          preloadedUser={preloadedUser}
          preloadedComparison={preloadedComparison}
        >
          {children}
        </Providers>
      </body>
    </html>
  );
}
