export const paths = {
  home: "/",
  signIn: "/sign-in",
  signUp: "/sign-up",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  profile: "/profile",
  cart: "/cart",
  productPage: "/product",
  aboutUs: "/about-us",
  reviews: "/reviews",
  blog: "/blog",
  contacts: "/contacts",
  paymentAndShipping: "/payment-and-shipping",
  privacyPolicy: "/privacy-policy",
  offerAgreement: "/offer-agreement",
  compare: "/compare",
  checkout: "/checkout",
};
